<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>044-async-fn-await.html</title>
</head>
<body>
	
</body>
<script type="text/javascript">
	
	/*async function fn(){
		//await只能放到async函数体中
		const data1 = await 'data1'

		console.log('get data1=',data1)

		console.log('do something...')

		return 'result data'

	}
	fn()

	.then(data=>{
		console.log(data)
	})
	*/








/*

	const promise = new Promise((resolve,reject)=>{
		setTimeout(()=>{
			resolve('success data')
		},200)
	})

	async function fn(){
		//await只能放到async函数体中
		const data1 = await promise

		console.log('get data1=',data1)

		console.log('do something...')

		return 'result data'

	}
	fn()

	.then(data=>{
		console.log(data)
	})

*/

















	const promise = new Promise((resolve,reject)=>{
		setTimeout(()=>{
			reject('reject data')
		},200)
	})

	async function fn(){
		//加到try-catch语句块预防出错
		try{
			const data1 = await promise
			console.log('get data1=',data1)
			console.log('do something...')
		}catch(err){
			console.log('handle err',err)
		}
		return 'result data'
	}
	fn()
	//.再次调用then(),返回return 的值
	.then(data=>{
		console.log(data)
	})








</script>
</html>